name: CI
run-name: Push ${{ github.workflow }} (${{ github.ref_name }})
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint:
    uses: yhiguchi-dev/reusable-workflow/.github/workflows/lint-with-pnpm.yaml@main
    with:
      node-version: ${{ matrix.node-version }}
      lint-command: lint
      working-directory: nextjs
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 20

  build:
    uses: yhiguchi-dev/reusable-workflow/.github/workflows/docker-image-push-to-ghcr.yaml@main
    with:
      build-context: ${{ matrix.build-context }}
    needs:
      - lint
    strategy:
      fail-fast: false
      matrix:
        build-context:
          - nextjs
