name: CI
run-name: ${{ github.workflow }} (${{ github.ref_name }})
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
env:
  NEXT_PUBLIC_BACKEND_URL: ${{ vars.BACKEND_URL }}
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm
          cache-dependency-path: ./nextjs/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
        working-directory: nextjs
      - name: Run lint
        run: pnpm lint
        working-directory: nextjs
#      - name: Run test
#        run: pnpm test
  build:
    runs-on: ubuntu-latest
    needs:
      - lint
    strategy:
      matrix:
        build-context:
          - nextjs
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build ${{ matrix.build-context }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.build-context }}
          load: true
          tags: ghcr.io/${{ github.repository }}-${{ matrix.build-context }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/${{ github.repository }}-${{ matrix.build-context }}:latest
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: CRITICAL,HIGH
      - name: Push ${{ matrix.build-context }}
        uses: docker/build-push-action@v4
        with:
          context: ./${{ matrix.build-context }}
          push: true
          tags: ghcr.io/${{ github.repository }}-${{ matrix.build-context }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max